# Generated by Django 4.1.3 on 2023-03-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='prices.market'),
            preserve_default=False,
        ),
    ]
