# Generated by Django 4.1.3 on 2023-03-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_market_item_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='market',
        ),
        migrations.AddField(
            model_name='purchase',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='prices.market'),
            preserve_default=False,
        ),
    ]
