# Generated by Django 4.1.3 on 2023-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_remove_item_market_purchase_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quality',
            field=models.FloatField(),
        ),
    ]
